[project]
name = "pointclouds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24.0",
    "open3d==0.19.0",
    "opencv-contrib-python>=4.8.0",
    "opencv-python>=4.8.0",
    "pyrealsense2>=2.56.5.9235",
    "pyvista>=0.47.1",
]

[dependency-groups]
dev = [
    "ty>=0.0.18",
]
